version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    TARGET_ACCOUNT_IDS: "861530259719 418272799989" 
    IMAGE_REPO_NAME: "demoimages"
    IMAGE_TAG: "latest"

phases:
  # The 'install' phase has been removed as it's not needed.
  # Docker is already included in the standard build image.
  
  pre_build:
    commands:
      - echo "Logging in to multiple ECR registries..."
      - |
        for account_id in $TARGET_ACCOUNT_IDS; do
          echo "Assuming role in account $account_id"
          CREDS=$(aws sts assume-role --role-arn arn:aws:iam::$account_id:role/Ai-house-ecr-lambda-sts --role-session-name "CodeBuild-ECR-Push-Session")
          
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Credentials.SessionToken)
          
          echo "Logging in to ECR for account $account_id"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $account_id.dkr.ecr.$AWS_REGION.amazonaws.com
          
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
        done

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - |
        for account_id in $TARGET_ACCOUNT_IDS; do
          echo "Tagging image for account $account_id"
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $account_id.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        done

  post_build:
    commands:
      - echo "Pushing Docker images to multiple ECR repositories..."
      - |
        for account_id in $TARGET_ACCOUNT_IDS; do
          echo "Pushing to $account_id.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
          docker push $account_id.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        done
