version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "9431432288443"
    ECR_REPOSITORY_NAME: "demoimages"
    LAMBDA_FUNCTION_NAME: "web-adapter-demo-ci-cd"
    CFN_S3_BUCKET: "ecr-lambda-ai-house-rnd"
    ECR_CFN_TEMPLATE: "AiHouse-ecr-lambda.yml"
    LAMBDA_CFN_TEMPLATE: "ai-house-lambda-function-template.yaml"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      # Use the unique Git commit hash for the image tag for best practice
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}

  build:
    commands:
      # All logic is now inside a single command block to prevent YAML syntax errors.
      # The 'set -e' command ensures the script will exit immediately if any command fails.
      - |
        set -e

        echo "--- Step 1: Check for ECR Repository ---"
        if ! aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME --region $AWS_DEFAULT_REGION > /dev/null 2>&1; then
          echo "ECR repository '$ECR_REPOSITORY_NAME' not found. Creating it with CloudFormation..."
          aws cloudformation create-stack \
            --stack-name Create-ECR-For-Pipeline \
            --template-url https://$CFN_S3_BUCKET.s3.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_CFN_TEMPLATE \
            --region $AWS_DEFAULT_REGION
          echo "Waiting for ECR stack creation to complete..."
          aws cloudformation wait stack-create-complete --stack-name Create-ECR-For-Pipeline --region $AWS_DEFAULT_REGION
          echo "ECR Repository created successfully."
        else
          echo "ECR repository '$ECR_REPOSITORY_NAME' already exists. Skipping creation."
        fi

        echo "--- Step 2: Build and Push Docker Image ---"
        echo "Building the Docker image with tag: $IMAGE_TAG"
        docker build -t $REPOSITORY_URI:$IMAGE_TAG .
        
        echo "Pushing the Docker image to ECR..."
        docker push $REPOSITORY_URI:$IMAGE_TAG

        echo "--- Step 3: Check for and Create/Update Lambda Function ---"
        if ! aws lambda get-function --function-name $LAMBDA_FUNCTION_NAME --region $AWS_DEFAULT_REGION > /dev/null 2>&1; then
          echo "Lambda function '$LAMBDA_FUNCTION_NAME' not found. Creating it now via CloudFormation..."
          aws cloudformation create-stack \
            --stack-name Create-Lambda-For-Pipeline \
            --template-url https://$CFN_S3_BUCKET.s3.$AWS_DEFAULT_REGION.amazonaws.com/$LAMBDA_CFN_TEMPLATE \
            --parameters ParameterKey=ImageUri,ParameterValue=$REPOSITORY_URI:$IMAGE_TAG \
            --capabilities CAPABILITY_IAM \
            --region $AWS_DEFAULT_REGION
          echo "Waiting for Lambda stack creation to complete..."
          aws cloudformation wait stack-create-complete --stack-name Create-Lambda-For-Pipeline --region $AWS_DEFAULT_REGION
          echo "Lambda function created successfully."
        else
          echo "Lambda function '$LAMBDA_FUNCTION_NAME' already exists. Updating its code with the new image..."
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri $REPOSITORY_URI:$IMAGE_TAG \
            --region $AWS_DEFAULT_REGION
          echo "Lambda function updated successfully."
        fi

        echo "Build and Deploy process completed."
